/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vcfs;
import static java.time.LocalDateTime.parse;
import javax.swing.JOptionPane;
import java.util.*;

/**
 * @author elm00516
 */
public class AdminScreen extends javax.swing.JFrame{
    //implements Observer
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminScreen.class.getName());

    private AdminController adminController;
    //private CareerFairSystem careerFairSystem;

    /**
     * Creates new form AdminScreen2
     */
    //public AdminScreen2(AdminController adminController, CareerFairSystem careerFairSystem) {
    public AdminScreen(AdminController adminController) {
        this.adminController = adminController;
        //this.careerFairSystem = careerFairSystem;
        
        initComponents();
        setVisible(true);
        setTitle("Admin Screen");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        //careerFairSystem.addObserver(this);
    }
    
    //public void update(Observable o, Object arg) {
        
        // Fetch (potentially) updated information and display it
        //adminController.getOpeningTimes();
        
        
    //} // update

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CurrentFairOpeningLabel = new javax.swing.JLabel();
        CurrentFairOpeningBox = new javax.swing.JTextField();
        CurrentFairClosingLabel = new javax.swing.JLabel();
        CurrentFairClosingBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        NewFairOpeningLabel = new javax.swing.JLabel();
        NewFairClosingLabel = new javax.swing.JLabel();
        NewFairOpeningDay = new javax.swing.JTextField();
        SlashOne = new javax.swing.JLabel();
        NewFairOpeningMonth = new javax.swing.JTextField();
        SlashTwo = new javax.swing.JLabel();
        NewFairOpeningYear = new javax.swing.JTextField();
        NewFairOpeningHour = new javax.swing.JTextField();
        ColonOne = new javax.swing.JLabel();
        NewFairOpeningMinute = new javax.swing.JTextField();
        NewFairClosingDay = new javax.swing.JTextField();
        SlashThree = new javax.swing.JLabel();
        NewFairClosingMonth = new javax.swing.JTextField();
        SlashFour = new javax.swing.JLabel();
        NewFairClosingYear = new javax.swing.JTextField();
        NewFairClosingHour = new javax.swing.JTextField();
        ColonTwo = new javax.swing.JLabel();
        NewFairClosingMinute = new javax.swing.JTextField();
        UpdateTimeButton = new javax.swing.JButton();
        CurrentBookingOpeningLabel = new javax.swing.JLabel();
        CurrentBookingOpeningBox = new javax.swing.JTextField();
        CurrentBookingClosingLabel = new javax.swing.JLabel();
        CurrentBookingClosingBox = new javax.swing.JTextField();
        NewBookingOpeningYear = new javax.swing.JTextField();
        NewBookingClosingMinute = new javax.swing.JTextField();
        NewBookingOpeningHour = new javax.swing.JTextField();
        ColonThree = new javax.swing.JLabel();
        NewBookingOpeningMinute = new javax.swing.JTextField();
        NewBookingOpeningLabel = new javax.swing.JLabel();
        NewBookingClosingLabel = new javax.swing.JLabel();
        NewBookingOpeningDay = new javax.swing.JTextField();
        SlashFive = new javax.swing.JLabel();
        NewBookingOpeningMonth = new javax.swing.JTextField();
        SlashSeven = new javax.swing.JLabel();
        NewBookingClosingMonth = new javax.swing.JTextField();
        SlashEight = new javax.swing.JLabel();
        NewBookingClosingYear = new javax.swing.JTextField();
        SlashSix = new javax.swing.JLabel();
        NewBookingClosingDay = new javax.swing.JTextField();
        NewBookingClosingHour = new javax.swing.JTextField();
        ColonFour = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NewOrganisationBox = new javax.swing.JTextField();
        AddOrganisationButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ResetFairDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CurrentFairOpeningLabel.setText("Current Fair Opening Time:");

        CurrentFairOpeningBox.setEditable(false);
        CurrentFairOpeningBox.setBackground(new java.awt.Color(255, 255, 255));
        CurrentFairOpeningBox.setFocusable(false);

        CurrentFairClosingLabel.setText("Current Fair Closing Time:");

        CurrentFairClosingBox.setEditable(false);
        CurrentFairClosingBox.setBackground(new java.awt.Color(255, 255, 255));
        CurrentFairClosingBox.setFocusable(false);

        NewFairOpeningLabel.setText("New Fair Opening Time:");

        NewFairClosingLabel.setText("New Fair Closing Time:");

        NewFairOpeningDay.setText("DD");
        NewFairOpeningDay.setToolTipText("");
        NewFairOpeningDay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NewFairOpeningDay.setName(""); // NOI18N

        SlashOne.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashOne.setText("/");

        NewFairOpeningMonth.setText("MM");

        SlashTwo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashTwo.setText("/");

        NewFairOpeningYear.setText("YYYY");

        NewFairOpeningHour.setText("HH");

        ColonOne.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ColonOne.setText(":");

        NewFairOpeningMinute.setText("MM");

        NewFairClosingDay.setText("DD");

        SlashThree.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashThree.setText("/");

        NewFairClosingMonth.setText("MM");

        SlashFour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashFour.setText("/");

        NewFairClosingYear.setText("YYYY");

        NewFairClosingHour.setText("HH");

        ColonTwo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ColonTwo.setText(":");

        NewFairClosingMinute.setText("MM");

        UpdateTimeButton.setText("Update Opening Times");
        UpdateTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTimeButtonActionPerformed(evt);
            }
        });

        CurrentBookingOpeningLabel.setText("Current Booking Opening Time:");

        CurrentBookingOpeningBox.setEditable(false);
        CurrentBookingOpeningBox.setBackground(new java.awt.Color(255, 255, 255));
        CurrentBookingOpeningBox.setFocusable(false);

        CurrentBookingClosingLabel.setText("Current Booking Closing Time:");

        CurrentBookingClosingBox.setEditable(false);
        CurrentBookingClosingBox.setBackground(new java.awt.Color(255, 255, 255));
        CurrentBookingClosingBox.setFocusable(false);

        NewBookingOpeningYear.setText("YYYY");

        NewBookingClosingMinute.setText("MM");

        NewBookingOpeningHour.setText("HH");

        ColonThree.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ColonThree.setText(":");

        NewBookingOpeningMinute.setText("MM");

        NewBookingOpeningLabel.setText("New Booking Opening Time:");

        NewBookingClosingLabel.setText("New Booking Closing Time:");

        NewBookingOpeningDay.setText("DD");
        NewBookingOpeningDay.setToolTipText("");
        NewBookingOpeningDay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NewBookingOpeningDay.setName(""); // NOI18N

        SlashFive.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashFive.setText("/");

        NewBookingOpeningMonth.setText("MM");

        SlashSeven.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashSeven.setText("/");

        NewBookingClosingMonth.setText("MM");

        SlashEight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashEight.setText("/");

        NewBookingClosingYear.setText("YYYY");

        SlashSix.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SlashSix.setText("/");

        NewBookingClosingDay.setText("DD");

        NewBookingClosingHour.setText("HH");

        ColonFour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ColonFour.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateTimeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NewFairOpeningLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewFairClosingDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashThree, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NewFairClosingMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashFour, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NewFairClosingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewFairOpeningDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashOne, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NewFairOpeningMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NewFairOpeningYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewFairOpeningHour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(ColonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(NewFairOpeningMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewFairClosingHour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(ColonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(NewFairClosingMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(NewFairClosingLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NewBookingOpeningLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewBookingClosingDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NewBookingClosingMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashEight, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NewBookingClosingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewBookingOpeningDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashFive, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NewBookingOpeningMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(SlashSix, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NewBookingOpeningYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewBookingOpeningHour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(ColonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(NewBookingOpeningMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NewBookingClosingHour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(ColonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(NewBookingClosingMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(NewBookingClosingLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentFairOpeningLabel)
                            .addComponent(CurrentFairOpeningBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentFairClosingLabel)
                            .addComponent(CurrentFairClosingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentBookingOpeningLabel)
                            .addComponent(CurrentBookingOpeningBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentBookingClosingLabel)
                            .addComponent(CurrentBookingClosingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentFairOpeningLabel)
                            .addComponent(CurrentBookingOpeningLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentFairOpeningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentFairClosingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentFairClosingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CurrentBookingOpeningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentBookingClosingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentBookingClosingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NewFairOpeningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewFairOpeningDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashOne)
                            .addComponent(NewFairOpeningMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashTwo)
                            .addComponent(NewFairOpeningYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewFairOpeningHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColonOne)
                            .addComponent(NewFairOpeningMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewFairClosingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewFairClosingDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashThree)
                            .addComponent(NewFairClosingMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashFour)
                            .addComponent(NewFairClosingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewFairClosingHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColonTwo)
                            .addComponent(NewFairClosingMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NewBookingOpeningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewBookingOpeningDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashFive)
                            .addComponent(NewBookingOpeningMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashSix)
                            .addComponent(NewBookingOpeningYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewBookingOpeningHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColonThree)
                            .addComponent(NewBookingOpeningMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewBookingClosingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewBookingClosingDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashSeven)
                            .addComponent(NewBookingClosingMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SlashEight)
                            .addComponent(NewBookingClosingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewBookingClosingHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColonFour)
                            .addComponent(NewBookingClosingMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateTimeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Update Opening Times", jPanel1);

        jLabel1.setText("New Organisation Name:");

        AddOrganisationButton.setText("Add Organisation");
        AddOrganisationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrganisationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NewOrganisationBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddOrganisationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewOrganisationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddOrganisationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Organisation", jPanel2);

        ResetFairDataButton.setText("Reset Fair Data");
        ResetFairDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFairDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(ResetFairDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(ResetFairDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset Fair Data", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>                        

    private void UpdateTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String dateFormat = "%s-%s-%sT%s:%s:%s";
        try{
            String newFairOpening = String.format(dateFormat, NewFairOpeningYear.getText(), NewFairOpeningMonth.getText(), NewFairOpeningDay.getText(), NewFairOpeningHour.getText(), NewFairOpeningMinute.getText(), "00");
            String newFairClosing = String.format(dateFormat, NewFairClosingYear.getText(), NewFairClosingMonth.getText(), NewFairClosingDay.getText(), NewFairClosingHour.getText(), NewFairClosingMinute.getText(), "00");
            String newBookingOpening = String.format(dateFormat, NewBookingOpeningYear.getText(), NewBookingOpeningMonth.getText(), NewBookingOpeningDay.getText(), NewBookingOpeningHour.getText(), NewBookingOpeningMinute.getText(), "00");
            String newBookingClosing = String.format(dateFormat, NewBookingClosingYear.getText(), NewBookingClosingMonth.getText(), NewBookingClosingDay.getText(), NewBookingClosingHour.getText(), NewBookingClosingMinute.getText(), "00");
            java.time.LocalDateTime starting = parse(newFairOpening);
            java.time.LocalDateTime ending = parse(newFairClosing);
            java.time.LocalDateTime opening = parse(newBookingOpening);
            java.time.LocalDateTime closing = parse(newBookingClosing);
            
            adminController.configureTimes(starting, ending, opening, closing);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Date", "Ensure valid dates are entered.", JOptionPane.ERROR_MESSAGE);
        }
    }                                                

    private void AddOrganisationButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        String newOrganisationName = NewOrganisationBox.getText();
        adminController.addOrganisation(newOrganisationName);
    }                                                     

    private void ResetFairDataButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        int selected = JOptionPane.showConfirmDialog(null, "Reset all fair data?", "Reset Fair Data", JOptionPane.YES_NO_OPTION);
        
        if(selected == JOptionPane.YES_OPTION){
           
            //Really make sure they want to reset
            selected = JOptionPane.showConfirmDialog(null, "Are you sure you want to reset all fair data?", "Reset Fair Data", JOptionPane.YES_NO_OPTION);
            if(selected == JOptionPane.YES_OPTION){
                adminController.resetFairData();
            }
        }
    }                                                   


    // Variables declaration - do not modify                     
    private javax.swing.JButton AddOrganisationButton;
    private javax.swing.JLabel ColonFour;
    private javax.swing.JLabel ColonOne;
    private javax.swing.JLabel ColonThree;
    private javax.swing.JLabel ColonTwo;
    private javax.swing.JTextField CurrentBookingClosingBox;
    private javax.swing.JLabel CurrentBookingClosingLabel;
    private javax.swing.JTextField CurrentBookingOpeningBox;
    private javax.swing.JLabel CurrentBookingOpeningLabel;
    private javax.swing.JTextField CurrentFairClosingBox;
    private javax.swing.JLabel CurrentFairClosingLabel;
    private javax.swing.JTextField CurrentFairOpeningBox;
    private javax.swing.JLabel CurrentFairOpeningLabel;
    private javax.swing.JTextField NewBookingClosingDay;
    private javax.swing.JTextField NewBookingClosingHour;
    private javax.swing.JLabel NewBookingClosingLabel;
    private javax.swing.JTextField NewBookingClosingMinute;
    private javax.swing.JTextField NewBookingClosingMonth;
    private javax.swing.JTextField NewBookingClosingYear;
    private javax.swing.JTextField NewBookingOpeningDay;
    private javax.swing.JTextField NewBookingOpeningHour;
    private javax.swing.JLabel NewBookingOpeningLabel;
    private javax.swing.JTextField NewBookingOpeningMinute;
    private javax.swing.JTextField NewBookingOpeningMonth;
    private javax.swing.JTextField NewBookingOpeningYear;
    private javax.swing.JTextField NewFairClosingDay;
    private javax.swing.JTextField NewFairClosingHour;
    private javax.swing.JLabel NewFairClosingLabel;
    private javax.swing.JTextField NewFairClosingMinute;
    private javax.swing.JTextField NewFairClosingMonth;
    private javax.swing.JTextField NewFairClosingYear;
    private javax.swing.JTextField NewFairOpeningDay;
    private javax.swing.JTextField NewFairOpeningHour;
    private javax.swing.JLabel NewFairOpeningLabel;
    private javax.swing.JTextField NewFairOpeningMinute;
    private javax.swing.JTextField NewFairOpeningMonth;
    private javax.swing.JTextField NewFairOpeningYear;
    private javax.swing.JTextField NewOrganisationBox;
    private javax.swing.JButton ResetFairDataButton;
    private javax.swing.JLabel SlashEight;
    private javax.swing.JLabel SlashFive;
    private javax.swing.JLabel SlashFour;
    private javax.swing.JLabel SlashOne;
    private javax.swing.JLabel SlashSeven;
    private javax.swing.JLabel SlashSix;
    private javax.swing.JLabel SlashThree;
    private javax.swing.JLabel SlashTwo;
    private javax.swing.JButton UpdateTimeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration                   
}
