package vcfs;

/**
 * @author elm00516
 */
public class CandidateScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CandidateScreen.class.getName());
    private CandidateController candidateController;
    private Candidate candidate;
    
    /**
     * Creates new form CandidateScreen
     */
    public CandidateScreen(CandidateController candidateController) {
        this.candidateController = candidateController;
        initComponents();
        setVisible(true);
        setTitle("Candidate Screen");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        DisplayNameLabel = new javax.swing.JLabel();
        DisplayNameBox = new javax.swing.JTextField();
        EmailAddressLabel = new javax.swing.JLabel();
        EmailAddressBox = new javax.swing.JTextField();
        CVSummaryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CVSummaryBox = new javax.swing.JTextArea();
        InterestTagsLabel = new javax.swing.JLabel();
        InterestTagsBox = new javax.swing.JTextField();
        RegisterCandidateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PreferredInterestTagsLabel = new javax.swing.JLabel();
        PreferredInterestTagsBox = new javax.swing.JTextField();
        PreferredOrganisationsLabel = new javax.swing.JLabel();
        PreferredOrganisationsBox = new javax.swing.JTextField();
        MaxAppointmentsLabel = new javax.swing.JLabel();
        MaxAppointmentsBox = new javax.swing.JTextField();
        AutoBookRequestButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ReservationIDLabel = new javax.swing.JLabel();
        ReservationIDBox = new javax.swing.JTextField();
        JoinSessionButton = new javax.swing.JButton();
        CancelReservationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayNameLabel.setText("Display Name:");

        EmailAddressLabel.setText("Email Address:");

        CVSummaryLabel.setText("CV Summary:");

        CVSummaryBox.setColumns(20);
        CVSummaryBox.setRows(4);
        jScrollPane1.setViewportView(CVSummaryBox);

        InterestTagsLabel.setText("Interest Tags:");

        InterestTagsBox.setToolTipText("Tags should be split with a comma");

        RegisterCandidateButton.setText("Register Candidate");
        RegisterCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCandidateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RegisterCandidateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CVSummaryLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisplayNameLabel)
                            .addComponent(DisplayNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailAddressLabel)
                            .addComponent(EmailAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InterestTagsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InterestTagsBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DisplayNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmailAddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CVSummaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InterestTagsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InterestTagsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterCandidateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Register New Candidate", jPanel1);

        PreferredInterestTagsLabel.setText("Preferred Interest Tags:");

        PreferredOrganisationsLabel.setText("Preferred Organisations:");

        MaxAppointmentsLabel.setText("Maximum Number of Appointments:");

        AutoBookRequestButton.setText("Create Auto-Book Request");
        AutoBookRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoBookRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PreferredInterestTagsLabel)
                            .addComponent(PreferredInterestTagsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PreferredOrganisationsLabel)
                            .addComponent(PreferredOrganisationsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxAppointmentsLabel)
                            .addComponent(MaxAppointmentsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(AutoBookRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PreferredOrganisationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PreferredOrganisationsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PreferredInterestTagsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PreferredInterestTagsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MaxAppointmentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaxAppointmentsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AutoBookRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Reservation Request", jPanel2);

        ReservationIDLabel.setText("Reservation ID:");

        JoinSessionButton.setText("Join Session");
        JoinSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinSessionButtonActionPerformed(evt);
            }
        });

        CancelReservationButton.setText("Cancel Reservation");
        CancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReservationIDLabel)
                            .addComponent(ReservationIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(CancelReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addComponent(JoinSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ReservationIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReservationIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JoinSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Reservations", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>                        

    private void AutoBookRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try{
            String[] interestTags = PreferredInterestTagsBox.getText().split(",");
            String[] organisations = PreferredOrganisationsBox.getText().split(",");
            int maxAppointments = Integer.valueOf(MaxAppointmentsBox.getText());

            candidateController.createRequest(candidate, interestTags, organisations, maxAppointments);
        }catch(Exception e){
        }

    }                                                     

    private void RegisterCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        try{
            String displayName = DisplayNameBox.getText();
            String emailAddress = EmailAddressBox.getText();
            String cvSummary = CVSummaryBox.getText();
            String[] interestTags = InterestTagsBox.getText().split(",");

            candidate = candidateController.registerCandidate(displayName, emailAddress, cvSummary, interestTags);

        }catch(Exception e){

        }
    }                                                       

    private void CancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        try{
            String reservationID = ReservationIDBox.getText();
            candidateController.cancelAsCandidate(candidate, reservationID);
        }catch(Exception e){
        }
    }                                                       

    private void JoinSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        try{
            String reservationID = ReservationIDBox.getText();
            candidateController.joinSession(candidate, reservationID);
        }catch(Exception e){
        }
    }                                                 

    // Variables declaration - do not modify                     
    private javax.swing.JButton AutoBookRequestButton;
    private javax.swing.JTextArea CVSummaryBox;
    private javax.swing.JLabel CVSummaryLabel;
    private javax.swing.JButton CancelReservationButton;
    private javax.swing.JTextField DisplayNameBox;
    private javax.swing.JLabel DisplayNameLabel;
    private javax.swing.JTextField EmailAddressBox;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JTextField InterestTagsBox;
    private javax.swing.JLabel InterestTagsLabel;
    private javax.swing.JButton JoinSessionButton;
    private javax.swing.JTextField MaxAppointmentsBox;
    private javax.swing.JLabel MaxAppointmentsLabel;
    private javax.swing.JTextField PreferredInterestTagsBox;
    private javax.swing.JLabel PreferredInterestTagsLabel;
    private javax.swing.JTextField PreferredOrganisationsBox;
    private javax.swing.JLabel PreferredOrganisationsLabel;
    private javax.swing.JButton RegisterCandidateButton;
    private javax.swing.JTextField ReservationIDBox;
    private javax.swing.JLabel ReservationIDLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration                   
}
